### ISSUE TITLE
Background vs foreground color

### ISSUE THREAD

**Issue by pornel** [whatwg/meta-theme-color#10]
Chrome uses theme-color as a background color of browser's toolbar and background of background Android app's title bar.

Safari 9 uses theme-color as a foreground color of pinned icons.

For a brand like FT, which is black text on a branded "pink" background, this causes a conflict. We use the light "pink" as the `theme-color` which so far works great everywhere except the new Safari. 

If we set `theme-color` to black to have an appropriate icon in Safari, it'll cause Chrome's UI to look unacceptably bad.

The spec doesn't define whether the theme color is supposed to be used as a foreground or background oclor, and whether it should be light or dark.

I think the spec must take a stance on that to stop different vendors interpreting this color in conflicting ways.

Because Safari's interpretation is new, and has other compatibility problems (caused by non-standard `mask` attribute) I hope Safari can still back out and the `theme-color` can be standardized to mean **background** color.

----

FT's logo is:

http://image.webservices.ft.com/v1/images/raw/fticon:brand-ft?format=jpg&bgcolor=fff1e0&quality=highest&source=example

and for the monochrome Safari icon we'd like to use:

http://image.webservices.ft.com/v1/images/raw/fticon:brand-ft?format=svg&source=example

but when Safari applies theme-color to it, it's a mess:

http://image.webservices.ft.com/v1/images/raw/fticon:brand-ft?format=svg&tint=fff1e0,fff1e0&source=example

**Comment by Tigt** [comment]
Could we try standardizing this in a CSS @-rule or in the manifest? I'm seeing suggestions for new tags to stick in the `<head>` like `<meta name="icon-mask-color">` and this is all looking to become the next favicon, in terms of [being a huge mess](http://realfavicongenerator.net/favicon_compatibility).

Anything would be better than having to add more junk on every uncacheable HTML page that only a fraction of browsers use.

**Comment by pornel** [comment]
@Tigt This isn't about adding a new meta, this is about fixing meta that already exists in the wild and has multiple implementations.

Also the manifest spec already has `theme_color` and *defers to this spec*, so this bug also affects the manifest spec.

**Comment by Tigt** [comment]
Gotcha. It's hard to tell sometimes with all the cruft that's built up around site identities.

**Comment by pornel** [comment]
I've updated the ticket with example images that hopefully illustrate why vague theme-color is a problem.

**Comment by laukstein** [comment]
@tigt, you can fallow **rel=mask-icon** proposal in https://github.com/whatwg/html/issues/110

**Comment by domenic** [comment]
If either Apple or Google is willing to change this, we're willing to change the spec to be more specific. Has that occurred since this was originally posted?

**Comment by kornelski** [comment]
Apple has changed to `<link rel=mask-icon color=…>`, so the problem with Safari is solved. 

Are there any big users of theme color apart from Chrome? If not, then it's back to being de-facto a background color.

**Comment by domenic** [comment]
Great! I'll move this to whatwg/html and hopefully when you have the time you can do this and #11 :)

**Comment by domenic** [comment]
Moved to https://github.com/whatwg/html/issues/803
