### ISSUE TITLE
Support legacy/vendor-prefixed version? 

### ISSUE THREAD

**Issue by marcoscaceres** [whatwg/meta-theme-color#3]
@tabatkins says: 
> * "msapplication-navbutton-color" only allows named and hex colors. 
> * "apple-mobile-web-app-status-bar-style" appears to accept the values 
> "default", "black", and "black-translucent", which we can define as 
> meaning, respectively, that the page has no brand color, that the 
> brand color is black, or that the brand color is rgba(0,0,0,.5) 
> (spitballing here, if someone can provide the real alpha that would be 
> great). 

Hixie says: 

> I think it would make sense to allow vendors to treat these all as 
independent values (in particular, we wouldn't want IE to be forced to 
extend their interpretation of "msapplication-TileColor" and 
"msapplication-navbutton-color" to be redundant), but I do think it would 
make sense to encourage UAs to draw colours from whichever values are 
provided, so that authors don't have to include different values for each 
browser.

**Comment by domenic** [comment]
In https://github.com/whatwg/html/pull/720 we ended up deciding against this for now.
