### ISSUE TITLE
Convert brand-color into a CSS feature (at rule, pseudo element or something)

### ISSUE THREAD

**Issue by phistuck** [whatwg/meta-theme-color#5]
Adding yet another meta tag to the page seems unnecessary and feels like going backwards. The first network packet is already too crowded.
Since this is a style and design feature - a presentation feature - it belongs in CSS.

You can find the discussion here -
https://groups.google.com/a/chromium.org/d/msg/blink-dev/nzRY-h_-_ig/WClEljhYFswJ

Basically, something like -
```
@media ui
{
 ::header, ::footer, ::top, ::bottom, ::chrome, ::brand,
 ::header:inactive, ::header:active, ::header:translucent
 {
  color: blue;
  background-color: white;
 }
}
```

**Comment by ashmind** [comment]
I just tried the current design for my app, and it is somewhat inconvenient even for a simple case with single primary color in LESS/SASS. In a preprocessor, I use a `$main-color`variable -- but there is no easy way to reuse it in `<meta>`.

**Comment by marcoscaceres** [comment]
@ashmind, I would suggest you file a bug on LESS/SASS instead - that's a limitation of the preprocessor (in that it doesn't integrate with HTML), but not something we can really do much about at the standards level right now (as this is not a CSS feature).

**Comment by Snugug** [comment]
@marcoscaceres I believe @ashmind is echoing my usecase. Generally speaking though, CSS Preprocessors like Less and Sass aim to be agnostic of everything except their domain (CSS). Without this strict decoupling, each preprocessor would need to be tightly integrated with the system producing HTML, thus strictly limiting their usefulness. Suggesting that they do so does runs counter to their stated purposes and does not resolve the underlying usecase that the domain for working with styling in the browser (I understand that this is not strictly in the browser, but around it, but that is a technical implementation detail that most practically won't see the split between) is CSS, not HTML meta tags, and it's not unreasonable for one to be able to expect that this styling can be contained within their stylesheets.

**Comment by ashmind** [comment]
@marcoscaceres I see your point to an extent, however it's not only a LESS feature.

In newer CSS I can have:

```css
:root {
  --main-color: blue;
}
```

This can be used to style everything but `theme-color` at the moment.

(of course `:root` isn't high enough even if `theme-color` was in CSS, but it could be some new global scope).

**Comment by Snugug** [comment]
@ashmind actually beat me to it. Having this draw from CSS Variables (or something similar) would allow them to be shared.

**Comment by domenic** [comment]
This doesn't seem to have happened. If you're interested in the CSSWG taking this up then a thread on www-style is the place to start.
