### ISSUE TITLE
Last brand-color element should win, rather than first one

### ISSUE THREAD

**Issue by johnmellor** [whatwg/meta-theme-color#6]
> the first successfully parsed "brand-color" meta element defines the page's "brand color". Any further "brand-color" meta elements have no effect.

This seems inconsistent with CSS and other meta tags like "viewport", where later duplicate definitions override earlier definitions.

For example if you append a new brand-color meta element to your <head> without removing the old one, it will have no effect, whereas with viewport meta tags appending a new one would override the old one.

Perhaps the "finding the brand color" algorithm should be modified to iterate through in reverse document order?

**Comment by marcoscaceres** [comment]
As this is in wide use now (and has been shipping for almost a year), we should just confirm what Chrome does and standardize use that. @mbai, can you confirm so we can close this?

**Comment by mbai** [comment]
Yes, this should be closed
